spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5433/db
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver