name: ci.yml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: checkstyle
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: setup
        uses: ./.github/actions/setup
      - name: execution of the checkstyle command
        run: ./mvnw checkstyle:check
        shell: bash


  build:
    name: builder
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        # ajouter le run ( le script du job )


  unit-tests:
    name: unit tests checker
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        # ajouter le run ( le script du job )
    needs: [build, lint]


  sonar:
    name: code quality checker
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        # ajouter le run ( le script du job )
    needs: unit-tests